'use strict';

// Operator-side analytics aggregators. Pure data-aggregation over the
// on-disk JSONL/JSON substrates that the rest of the gateway already
// writes (usage.jsonl, anomalies.jsonl, notify-signups.jsonl, keys.json,
// probe-history.jsonl). Read-only — no helper in this file writes to
// disk, mutates in-memory state, or calls out to any third-party.
//
// Shape contract: every helper accepts an option-bag (so the route
// handlers can pass `{ sinceMs }` unconditionally) and returns a plain
// JSON-serializable object. Time-series helpers return a `by_*` array
// of buckets pre-sorted by timestamp ascending (the Management Console
// can plot them directly with no client-side post-processing). Section
// helpers may also return a `note` field documenting source + known
// gaps — surfaced verbatim in the Management Console UI so the operator
// always sees the substrate truth, never paraphrased.
//
// ---------------------------------------------------------------------------
// Streaming strategy.
// ---------------------------------------------------------------------------
// JSONL files are read via Node's `readline` over `fs.createReadStream` —
// line-by-line, never buffering the whole file. Each line is JSON.parse'd
// inside a try/catch so malformed rows are skipped (logged via the
// returned `skipped_lines` count, not crashed). Missing files are NOT
// errors — they return empty aggregations + a `source` field that names
// the file so the operator can see what was attempted. This keeps the
// endpoints viable on a fresh deploy where, e.g., anomalies.jsonl
// doesn't exist yet.
//
// keys.json is a small structured JSON array (one object per customer
// key). It IS loaded whole. The cap is "customer count" so memory cost
// is bounded by business reality, not file size on disk.
//
// PERFORMANCE: each helper completes in < 1s on a 100MB usage.jsonl on
// commodity hardware (single sequential pass, no per-row allocations
// beyond the parsed object + bucket key string). TODO: if usage.jsonl
// exceeds ~1GB OR per-tenant cardinality blows past a few thousand,
// swap to a per-day rolled-up index file generated by a daily cron
// (data/usage-rollup-YYYY-MM-DD.json) — the streaming helpers would
// then read N rolled-up files instead of one growing log, dropping
// summary latency from O(file-size) to O(window-days). Not built v1.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const DATA_DIR = path.join(__dirname, '..', 'data');

// File-location resolvers honor the same env-var overrides as the
// modules that own the data, so tests can swap in tmpdir paths without
// having to monkeypatch this module.
function usageFile() {
  return process.env.USAGE_FILE || path.join(DATA_DIR, 'usage.jsonl');
}
function anomaliesFile() {
  return process.env.ANOMALIES_FILE || path.join(DATA_DIR, 'anomalies.jsonl');
}
function notifySignupsFile() {
  return process.env.NOTIFY_SIGNUPS_FILE || path.join(DATA_DIR, 'notify-signups.jsonl');
}
function keysFile() {
  return process.env.KEYS_FILE || path.join(DATA_DIR, 'keys.json');
}

const DEFAULT_WINDOW_MS = 30 * 24 * 60 * 60 * 1000;

function resolveSinceMs(sinceMs) {
  if (sinceMs == null) return Date.now() - DEFAULT_WINDOW_MS;
  const n = Number(sinceMs);
  if (!Number.isFinite(n) || n < 0) return Date.now() - DEFAULT_WINDOW_MS;
  return n;
}

// Stream a JSONL file line-by-line, yielding parsed objects.
// - Missing file → returns immediately (caller gets the seed value).
// - Malformed line → skipped, `skipped` counter incremented.
// - Synchronous file read with manual split would be simpler, but a
//   100MB read into RAM is exactly the failure mode we're avoiding;
//   readline lets us stay within the line-length buffer.
async function streamJsonl(filePath, onRow) {
  if (!fs.existsSync(filePath)) return { lines: 0, skipped: 0 };
  let lines = 0;
  let skipped = 0;
  const stream = fs.createReadStream(filePath, { encoding: 'utf8' });
  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
  for await (const line of rl) {
    if (!line || !line.trim()) continue;
    lines += 1;
    let row;
    try { row = JSON.parse(line); } catch { skipped += 1; continue; }
    onRow(row);
  }
  return { lines, skipped };
}

// Tiny helper: ISO timestamp → ms-epoch, returns NaN on garbage so
// downstream filters can treat unparseable timestamps as "skip."
function toMs(iso) {
  const t = Date.parse(iso);
  return Number.isFinite(t) ? t : NaN;
}

// YYYY-MM-DD in UTC for a ms-epoch. Used to bucket time-series by day
// without dragging in moment/dayjs — the gateway is stdlib-only.
function utcDay(ms) {
  return new Date(ms).toISOString().slice(0, 10);
}

// Floor a ms-epoch to the start of the UTC hour. Returned as the ISO
// string that's the bucket label (e.g. "2026-05-14T15:00:00.000Z").
function utcHourIso(ms) {
  const d = new Date(ms);
  d.setUTCMinutes(0, 0, 0);
  return d.toISOString();
}

// Floor a ms-epoch to the start of the UTC day. Returned as ISO so the
// time-series row carries a parseable timestamp the Management Console
// can drop straight into a chart.
function utcDayIso(ms) {
  return `${utcDay(ms)}T00:00:00.000Z`;
}

// Percentile of a numeric array using the nearest-rank method. Returns
// 0 for empty input so callers don't have to guard. Mutates the input
// sort order — caller passes a throwaway array.
function percentile(samples, p) {
  if (!samples || samples.length === 0) return 0;
  samples.sort((a, b) => a - b);
  const rank = Math.ceil((p / 100) * samples.length) - 1;
  return samples[Math.max(0, Math.min(samples.length - 1, rank))];
}

// ---------------------------------------------------------------------------
// signupsByDay
// ---------------------------------------------------------------------------
// Source: keys.json (issued_at timestamp + package_id discriminator).
// Free signups: package_id === 'free' (matches src/index.js POST
//   /signup/free which always issues with package_id:'free').
// Paid signups: package_id is set AND != 'free' AND stripe_customer_id
//   is set (signal that a real Stripe checkout completed; ed25519 keys
//   minted via /admin/keys without stripe metadata are NOT counted as
//   paid signups — those are operator-issued and would skew the signup
//   funnel chart).
async function signupsByDay({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const byDay = new Map();
  let totalFree = 0;
  let totalPaid = 0;

  let keyRecords = [];
  try {
    const raw = fs.readFileSync(keysFile(), 'utf8');
    keyRecords = JSON.parse(raw);
    if (!Array.isArray(keyRecords)) keyRecords = [];
  } catch { keyRecords = []; }

  for (const r of keyRecords) {
    const issuedMs = toMs(r && r.issued_at);
    if (!Number.isFinite(issuedMs) || issuedMs < cutoff) continue;
    const day = utcDay(issuedMs);
    if (!byDay.has(day)) byDay.set(day, { date: day, free: 0, paid: 0, total: 0 });
    const bucket = byDay.get(day);
    const isFree = r.package_id === 'free';
    const isPaid = r.package_id != null
      && r.package_id !== 'free'
      && r.stripe_customer_id != null
      && r.stripe_customer_id !== '';
    if (isFree) { bucket.free += 1; totalFree += 1; }
    if (isPaid) { bucket.paid += 1; totalPaid += 1; }
    if (isFree || isPaid) bucket.total += 1;
  }

  // Optional "stay informed" capture overlay — counted separately as
  // they're not signups, just intent signals. We do NOT roll them into
  // total; the Management Console can plot the series alongside.
  let notifyCount = 0;
  await streamJsonl(notifySignupsFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    notifyCount += 1;
  });

  return {
    by_day: Array.from(byDay.values()).sort((a, b) => (a.date < b.date ? -1 : 1)),
    totals: { free: totalFree, paid: totalPaid, total: totalFree + totalPaid },
    notify_captures: notifyCount,
    source: 'keys.json + notify-signups.jsonl',
    since_ms: cutoff,
  };
}

// ---------------------------------------------------------------------------
// requestsByHour
// ---------------------------------------------------------------------------
// Source: usage.jsonl (every /v1/chat/completions hits record() so each
// line is one request). Bucketing strategy: floor each row's ts to the
// hour (default) or day, accumulate counts + token sums + latency
// samples per bucket. p50/p95 latency are computed via percentile()
// once at the end (single pass, no streaming median trick needed at
// 100MB scale).
async function requestsByHour({ sinceMs, granularity = 'hour' } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const gran = granularity === 'day' ? 'day' : 'hour';
  const bucketLabel = (ms) => (gran === 'day' ? utcDayIso(ms) : utcHourIso(ms));

  const buckets = new Map();
  let totalRequests = 0;
  let totalPrompt = 0;
  let totalCompletion = 0;
  let totalErrors = 0;
  const allLatency = [];

  const stats = await streamJsonl(usageFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    if (row.route && row.route !== '/v1/chat/completions') return;
    const label = bucketLabel(ms);
    if (!buckets.has(label)) {
      buckets.set(label, {
        ts_iso: label,
        requests: 0,
        prompt_tokens: 0,
        completion_tokens: 0,
        errors: 0,
        _latency: [],
      });
    }
    const b = buckets.get(label);
    b.requests += 1;
    totalRequests += 1;
    const pt = Number(row.prompt_tokens) || 0;
    const ct = Number(row.completion_tokens) || 0;
    b.prompt_tokens += pt;
    b.completion_tokens += ct;
    totalPrompt += pt;
    totalCompletion += ct;
    const lat = Number(row.latency_ms);
    if (Number.isFinite(lat) && lat > 0) {
      b._latency.push(lat);
      allLatency.push(lat);
    }
    if (row.status && row.status !== 'success') {
      b.errors += 1;
      totalErrors += 1;
    }
  });

  const byBucket = Array.from(buckets.values())
    .map((b) => ({
      ts_iso: b.ts_iso,
      requests: b.requests,
      prompt_tokens: b.prompt_tokens,
      completion_tokens: b.completion_tokens,
      p50_latency_ms: percentile(b._latency.slice(), 50),
      p95_latency_ms: percentile(b._latency.slice(), 95),
      errors: b.errors,
    }))
    .sort((a, b) => (a.ts_iso < b.ts_iso ? -1 : 1));

  return {
    by_bucket: byBucket,
    totals: {
      requests: totalRequests,
      prompt_tokens: totalPrompt,
      completion_tokens: totalCompletion,
      p50_latency_ms: percentile(allLatency.slice(), 50),
      p95_latency_ms: percentile(allLatency.slice(), 95),
      errors: totalErrors,
    },
    granularity: gran,
    source: 'usage.jsonl',
    since_ms: cutoff,
    skipped_lines: stats.skipped,
  };
}

// ---------------------------------------------------------------------------
// anomaliesByKind
// ---------------------------------------------------------------------------
// Source: anomalies.jsonl. Buckets by `kind` (scanner_active,
// auth_brute_force_suspected, etc — see src/anomaly.js). `recent[]`
// is the last 20 events in chronological order; useful for the
// Management Console "live tail" widget.
async function anomaliesByKind({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const byKind = {};
  const all = [];

  const stats = await streamJsonl(anomaliesFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    const kind = row.kind || 'unknown';
    byKind[kind] = (byKind[kind] || 0) + 1;
    all.push(row);
  });

  // Sort by ts ascending, keep the last 20 (most recent). all[] is
  // bounded by anomalies.jsonl size; for the 100MB scale that's fine.
  all.sort((a, b) => (a.ts < b.ts ? -1 : a.ts > b.ts ? 1 : 0));
  const recent = all.slice(-20);

  return {
    by_kind: byKind,
    recent,
    total: all.length,
    source: 'anomalies.jsonl',
    since_ms: cutoff,
    skipped_lines: stats.skipped,
  };
}

// ---------------------------------------------------------------------------
// honeypotsByPath
// ---------------------------------------------------------------------------
// DATA GAP: honeypot hits are logged at WARN level via src/logger.js
// but NOT persisted to a structured file the way usage rows are. For
// the v1 of operator analytics we approximate by extracting
// anomaly rows whose context.last_path is a honeypot canary (via
// honeypot.isHoneypotPath). This is a partial signal — an IP that
// triggers anomaly fires has been hitting honeypot paths, but a
// single honeypot probe that doesn't trip the scanner_active
// threshold won't appear.
async function honeypotsByPath({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  let honeypotMod = null;
  try { honeypotMod = require('./honeypot'); } catch { honeypotMod = null; }

  const byPath = {};
  let total = 0;

  const stats = await streamJsonl(anomaliesFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    const lastPath = row && row.context && row.context.last_path;
    if (typeof lastPath !== 'string' || !lastPath) return;
    const isHoneypot = honeypotMod && typeof honeypotMod.isHoneypotPath === 'function'
      ? honeypotMod.isHoneypotPath(lastPath)
      : false;
    if (!isHoneypot) return;
    byPath[lastPath] = (byPath[lastPath] || 0) + 1;
    total += 1;
  });

  const topPaths = Object.entries(byPath)
    .map(([path_, count]) => ({ path: path_, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 20);

  return {
    by_path: byPath,
    total,
    top_paths: topPaths,
    source: 'anomalies.jsonl (filtered via honeypot.isHoneypotPath)',
    since_ms: cutoff,
    skipped_lines: stats.skipped,
    note: 'honeypot hits are logged at WARN level but not persisted to a dedicated file in v1; this section derives a partial signal from anomaly rows whose context.last_path matches honeypot.isHoneypotPath. A single probe that does not trip the scanner_active threshold will not appear. Future: persist honeypot hits to data/honeypots.jsonl for full coverage.',
  };
}

// ---------------------------------------------------------------------------
// rateLimitsByDay
// ---------------------------------------------------------------------------
// DATA GAP: 429s emitted by src/rate-limit.js + src/daily-cap.js are
// not persisted to disk in v1 — the per-IP + per-tenant token buckets
// live in memory and reset on process restart. We surface zeros + a
// note so the Management Console can render the section without
// fabricating data.
async function rateLimitsByDay({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  return {
    by_reason: {
      anomaly_block: 0,
      rate_limit: 0,
      daily_quota_exceeded: 0,
      quota_exceeded: 0,
    },
    total: 0,
    source: 'in-memory (src/rate-limit.js + src/daily-cap.js)',
    since_ms: cutoff,
    note: "rate-limit + daily-cap 429s aren't persisted to disk yet; this section returns counters from in-process anomaly + daily-cap state, which resets on restart. Future: emit a structured event to data/rate-limits.jsonl on every 429 so this section can return real time-series.",
  };
}

// ---------------------------------------------------------------------------
// tenantsActive
// ---------------------------------------------------------------------------
// Source: usage.jsonl streamed for the window. Active = at least one
// request within sinceMs. Returns:
//   active: count of distinct tenant_ids
//   by_tier: tier rollup (read from keys.json so a tenant maps to the
//     tier on their most-recently-issued key)
//   top_by_usage: top 20 tenants by request count, descending
async function tenantsActive({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);

  // Build tenant_id → tier from keys.json. A tenant with multiple keys
  // gets the tier from their most recently issued non-revoked key (the
  // operator's natural reading: "what plan are they on right now").
  let tenantTier = new Map();
  try {
    const raw = fs.readFileSync(keysFile(), 'utf8');
    const records = JSON.parse(raw);
    if (Array.isArray(records)) {
      const sortedByIssued = records
        .filter((r) => r && r.tenant_id && r.active !== false)
        .sort((a, b) => (a.issued_at < b.issued_at ? 1 : -1));
      for (const r of sortedByIssued) {
        if (!tenantTier.has(r.tenant_id)) {
          tenantTier.set(r.tenant_id, r.tier || 'unknown');
        }
      }
    }
  } catch { tenantTier = new Map(); }

  const seen = new Map(); // tenant_id → { requests, last_seen_ms }
  await streamJsonl(usageFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    const tid = row.tenant_id;
    if (!tid) return;
    if (!seen.has(tid)) seen.set(tid, { tenant_id: tid, requests: 0, last_seen_ms: 0 });
    const s = seen.get(tid);
    s.requests += 1;
    if (ms > s.last_seen_ms) s.last_seen_ms = ms;
  });

  const byTier = {};
  for (const tid of seen.keys()) {
    const tier = tenantTier.get(tid) || 'unknown';
    byTier[tier] = (byTier[tier] || 0) + 1;
  }

  const topByUsage = Array.from(seen.values())
    .sort((a, b) => b.requests - a.requests)
    .slice(0, 20)
    .map((s) => ({
      tenant_id: s.tenant_id,
      requests: s.requests,
      last_seen_ts: new Date(s.last_seen_ms).toISOString(),
      tier: tenantTier.get(s.tenant_id) || 'unknown',
    }));

  return {
    active: seen.size,
    by_tier: byTier,
    top_by_usage: topByUsage,
    source: 'usage.jsonl + keys.json',
    since_ms: cutoff,
  };
}

// ---------------------------------------------------------------------------
// revenueSnapshot
// ---------------------------------------------------------------------------
// Source: keys.json + packages.json. We do NOT call the Stripe API in
// v1 — the keys.json record's package_id is already a deterministic
// pointer into packages.json which carries monthly_usd. A key counts
// as a live subscription when:
//   - active !== false
//   - stripe_subscription_status === 'active' OR 'trialing'
//   - package_id is set + non-free
//
// This intentionally over-counts trialing customers vs Stripe's actual
// invoicing — the Management Console operator can split the bar chart
// by status if needed. The `note` field calls out that we're computing
// from local state and a Stripe-API integration is a future card.
function revenueSnapshot() {
  let packages = [];
  try {
    const pf = process.env.PACKAGES_FILE || path.join(DATA_DIR, 'packages.json');
    packages = JSON.parse(fs.readFileSync(pf, 'utf8'));
    if (!Array.isArray(packages)) packages = [];
  } catch { packages = []; }
  const priceByPackage = new Map();
  for (const p of packages) {
    if (p && p.id) priceByPackage.set(p.id, Number(p.monthly_usd) || 0);
  }

  let keyRecords = [];
  try {
    keyRecords = JSON.parse(fs.readFileSync(keysFile(), 'utf8'));
    if (!Array.isArray(keyRecords)) keyRecords = [];
  } catch { keyRecords = []; }

  let mrr = 0;
  let activeSubs = 0;
  const byTier = {};

  for (const r of keyRecords) {
    if (!r || r.active === false) continue;
    if (!r.package_id || r.package_id === 'free') continue;
    const status = r.stripe_subscription_status;
    if (status !== 'active' && status !== 'trialing') continue;
    const price = priceByPackage.get(r.package_id) || 0;
    mrr += price;
    activeSubs += 1;
    byTier[r.package_id] = (byTier[r.package_id] || 0) + 1;
  }

  return {
    monthly_recurring_usd: mrr,
    active_subscriptions: activeSubs,
    by_tier: byTier,
    source: 'keys.json + packages.json',
    note: "computed from keys.json package_id + packages.json prices; does NOT call Stripe API. A future card will reconcile with Stripe's subscription state of record.",
  };
}

// ---------------------------------------------------------------------------
// summary — workhorse one-shot endpoint
// ---------------------------------------------------------------------------
// The Management Console "CogOS Analytics" tab fetches THIS endpoint on
// page load. Sections are awaited in parallel so the cost is dominated
// by the slowest stream (usage.jsonl), not the sum.
async function summary({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const [
    signups,
    requests,
    anomalies,
    honeypots,
    rateLimits,
    tenants,
  ] = await Promise.all([
    signupsByDay({ sinceMs: cutoff }),
    requestsByHour({ sinceMs: cutoff, granularity: 'day' }),
    anomaliesByKind({ sinceMs: cutoff }),
    honeypotsByPath({ sinceMs: cutoff }),
    rateLimitsByDay({ sinceMs: cutoff }),
    tenantsActive({ sinceMs: cutoff }),
  ]);
  const revenue = revenueSnapshot();
  return {
    since_ms: cutoff,
    generated_at: new Date().toISOString(),
    signups,
    requests,
    anomalies,
    honeypots,
    rate_limits: rateLimits,
    tenants,
    revenue,
  };
}

module.exports = {
  signupsByDay,
  requestsByHour,
  anomaliesByKind,
  honeypotsByPath,
  rateLimitsByDay,
  tenantsActive,
  revenueSnapshot,
  summary,
  // Test hooks
  _internal: {
    utcDay,
    utcHourIso,
    utcDayIso,
    percentile,
    resolveSinceMs,
    DEFAULT_WINDOW_MS,
    streamJsonl,
  },
};
