'use strict';

// Operator-side analytics aggregators. Pure data-aggregation over the
// on-disk JSONL/JSON substrates that the rest of the gateway already
// writes (usage.jsonl, anomalies.jsonl, notify-signups.jsonl, keys.json,
// probe-history.jsonl). Read-only — no helper in this file writes to
// disk, mutates in-memory state, or calls out to any third-party.
//
// Shape contract: every helper accepts an option-bag (so the route
// handlers can pass `{ sinceMs }` unconditionally) and returns a plain
// JSON-serializable object. Time-series helpers return a `by_*` array
// of buckets pre-sorted by timestamp ascending (the Management Console
// can plot them directly with no client-side post-processing). Section
// helpers may also return a `note` field documenting source + known
// gaps — surfaced verbatim in the Management Console UI so the operator
// always sees the substrate truth, never paraphrased.
//
// ---------------------------------------------------------------------------
// Streaming strategy.
// ---------------------------------------------------------------------------
// JSONL files are read via Node's `readline` over `fs.createReadStream` —
// line-by-line, never buffering the whole file. Each line is JSON.parse'd
// inside a try/catch so malformed rows are skipped (logged via the
// returned `skipped_lines` count, not crashed). Missing files are NOT
// errors — they return empty aggregations + a `source` field that names
// the file so the operator can see what was attempted. This keeps the
// endpoints viable on a fresh deploy where, e.g., anomalies.jsonl
// doesn't exist yet.
//
// keys.json is a small structured JSON array (one object per customer
// key). It IS loaded whole. The cap is "customer count" so memory cost
// is bounded by business reality, not file size on disk.
//
// PERFORMANCE: each helper completes in < 1s on a 100MB usage.jsonl on
// commodity hardware (single sequential pass, no per-row allocations
// beyond the parsed object + bucket key string). TODO: if usage.jsonl
// exceeds ~1GB OR per-tenant cardinality blows past a few thousand,
// swap to a per-day rolled-up index file generated by a daily cron
// (data/usage-rollup-YYYY-MM-DD.json) — the streaming helpers would
// then read N rolled-up files instead of one growing log, dropping
// summary latency from O(file-size) to O(window-days). Not built v1.
// ---------------------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const usageRollup = require('./usage-rollup');

const DATA_DIR = path.join(__dirname, '..', 'data');

// File-location resolvers honor the same env-var overrides as the
// modules that own the data, so tests can swap in tmpdir paths without
// having to monkeypatch this module.
function usageFile() {
  return process.env.USAGE_FILE || path.join(DATA_DIR, 'usage.jsonl');
}
function anomaliesFile() {
  return process.env.ANOMALIES_FILE || path.join(DATA_DIR, 'anomalies.jsonl');
}
function notifySignupsFile() {
  return process.env.NOTIFY_SIGNUPS_FILE || path.join(DATA_DIR, 'notify-signups.jsonl');
}
function keysFile() {
  return process.env.KEYS_FILE || path.join(DATA_DIR, 'keys.json');
}
function honeypotsFile() {
  return process.env.HONEYPOTS_FILE || path.join(DATA_DIR, 'honeypots.jsonl');
}
function rateLimitsFile() {
  return process.env.RATE_LIMITS_FILE || path.join(DATA_DIR, 'rate-limits.jsonl');
}

const DEFAULT_WINDOW_MS = 30 * 24 * 60 * 60 * 1000;

function resolveSinceMs(sinceMs) {
  if (sinceMs == null) return Date.now() - DEFAULT_WINDOW_MS;
  const n = Number(sinceMs);
  if (!Number.isFinite(n) || n < 0) return Date.now() - DEFAULT_WINDOW_MS;
  return n;
}

// Stream a JSONL file line-by-line, yielding parsed objects.
// - Missing file → returns immediately (caller gets the seed value).
// - Malformed line → skipped, `skipped` counter incremented.
// - Synchronous file read with manual split would be simpler, but a
//   100MB read into RAM is exactly the failure mode we're avoiding;
//   readline lets us stay within the line-length buffer.
async function streamJsonl(filePath, onRow) {
  if (!fs.existsSync(filePath)) return { lines: 0, skipped: 0 };
  let lines = 0;
  let skipped = 0;
  const stream = fs.createReadStream(filePath, { encoding: 'utf8' });
  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
  for await (const line of rl) {
    if (!line || !line.trim()) continue;
    lines += 1;
    let row;
    try { row = JSON.parse(line); } catch { skipped += 1; continue; }
    onRow(row);
  }
  return { lines, skipped };
}

// Tiny helper: ISO timestamp → ms-epoch, returns NaN on garbage so
// downstream filters can treat unparseable timestamps as "skip."
function toMs(iso) {
  const t = Date.parse(iso);
  return Number.isFinite(t) ? t : NaN;
}

// YYYY-MM-DD in UTC for a ms-epoch. Used to bucket time-series by day
// without dragging in moment/dayjs — the gateway is stdlib-only.
function utcDay(ms) {
  return new Date(ms).toISOString().slice(0, 10);
}

// Floor a ms-epoch to the start of the UTC hour. Returned as the ISO
// string that's the bucket label (e.g. "2026-05-14T15:00:00.000Z").
function utcHourIso(ms) {
  const d = new Date(ms);
  d.setUTCMinutes(0, 0, 0);
  return d.toISOString();
}

// Floor a ms-epoch to the start of the UTC day. Returned as ISO so the
// time-series row carries a parseable timestamp the Management Console
// can drop straight into a chart.
function utcDayIso(ms) {
  return `${utcDay(ms)}T00:00:00.000Z`;
}

// Percentile of a numeric array using the nearest-rank method. Returns
// 0 for empty input so callers don't have to guard. Mutates the input
// sort order — caller passes a throwaway array.
function percentile(samples, p) {
  if (!samples || samples.length === 0) return 0;
  samples.sort((a, b) => a - b);
  const rank = Math.ceil((p / 100) * samples.length) - 1;
  return samples[Math.max(0, Math.min(samples.length - 1, rank))];
}

// ---------------------------------------------------------------------------
// signupsByDay
// ---------------------------------------------------------------------------
// Source: keys.json (issued_at timestamp + package_id discriminator).
// Free signups: package_id === 'free' (matches src/index.js POST
//   /signup/free which always issues with package_id:'free').
// Paid signups: package_id is set AND != 'free' AND stripe_customer_id
//   is set (signal that a real Stripe checkout completed; ed25519 keys
//   minted via /admin/keys without stripe metadata are NOT counted as
//   paid signups — those are operator-issued and would skew the signup
//   funnel chart).
async function signupsByDay({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const byDay = new Map();
  let totalFree = 0;
  let totalPaid = 0;

  let keyRecords = [];
  try {
    const raw = fs.readFileSync(keysFile(), 'utf8');
    keyRecords = JSON.parse(raw);
    if (!Array.isArray(keyRecords)) keyRecords = [];
  } catch { keyRecords = []; }

  for (const r of keyRecords) {
    const issuedMs = toMs(r && r.issued_at);
    if (!Number.isFinite(issuedMs) || issuedMs < cutoff) continue;
    const day = utcDay(issuedMs);
    if (!byDay.has(day)) byDay.set(day, { date: day, free: 0, paid: 0, total: 0 });
    const bucket = byDay.get(day);
    const isFree = r.package_id === 'free';
    const isPaid = r.package_id != null
      && r.package_id !== 'free'
      && r.stripe_customer_id != null
      && r.stripe_customer_id !== '';
    if (isFree) { bucket.free += 1; totalFree += 1; }
    if (isPaid) { bucket.paid += 1; totalPaid += 1; }
    if (isFree || isPaid) bucket.total += 1;
  }

  // Optional "stay informed" capture overlay — counted separately as
  // they're not signups, just intent signals. We do NOT roll them into
  // total; the Management Console can plot the series alongside.
  let notifyCount = 0;
  await streamJsonl(notifySignupsFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    notifyCount += 1;
  });

  return {
    by_day: Array.from(byDay.values()).sort((a, b) => (a.date < b.date ? -1 : 1)),
    totals: { free: totalFree, paid: totalPaid, total: totalFree + totalPaid },
    notify_captures: notifyCount,
    source: 'keys.json + notify-signups.jsonl',
    since_ms: cutoff,
  };
}

// ---------------------------------------------------------------------------
// requestsByHour
// ---------------------------------------------------------------------------
// Source: usage.jsonl (every /v1/chat/completions hits record() so each
// line is one request) PLUS daily rollup index (src/usage-rollup.js).
// Bucketing strategy: floor each row's ts to the hour (default) or day,
// accumulate counts + token sums + latency samples per bucket. p50/p95
// latency are computed via percentile() once at the end.
//
// ROLLUP CACHE PATH (added at scale): if a UTC date inside [cutoff, today]
// has a pre-computed rollup file, we READ THAT FILE instead of streaming
// usage.jsonl rows for that date. The rollup carries per-hour buckets
// (granularity='hour') OR per-day globals (granularity='day') already
// aggregated + a sampled latency array for percentile reconstruction.
// usage.jsonl is still streamed for the in-progress UTC day (today) and
// any days without a rollup yet. The streaming pass is restricted to
// those dates by checking utcDay(ms) against the rollup-set; rows whose
// date is covered by a rollup are skipped to avoid double-counting.
//
// Correctness: counts + token sums are exact (rollup is a deterministic
// re-aggregation of the same rows). Percentiles are computed by merging
// the sampled-latency arrays from each consumed rollup with the live
// latency samples from the streamed days — this yields an honest
// nearest-rank percentile over the union of samples (median-of-medians
// is wrong, sample-merge is correct).
//
// The rollup is a CACHE — if a late-arriving row is appended for a date
// that already has a rollup, the rollup's row_count will diverge from
// the truth. computeMissingRollups() only writes rollups for COMPLETE
// days (date < today UTC) so the only way to hit drift is an out-of-
// order ts on a row appended AFTER the day boundary; in that case the
// operator can force-recompute via computeDayRollup(date) and the
// cache realigns.
async function requestsByHour({ sinceMs, granularity = 'hour' } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const gran = granularity === 'day' ? 'day' : 'hour';
  const bucketLabel = (ms) => (gran === 'day' ? utcDayIso(ms) : utcHourIso(ms));

  const buckets = new Map();
  let totalRequests = 0;
  let totalPrompt = 0;
  let totalCompletion = 0;
  let totalErrors = 0;
  const allLatency = [];

  // Compute the set of UTC dates we might cover with rollups. Only
  // COMPLETE days (date < today UTC) can have rollups; today's data is
  // streamed live.
  const cutoffDay = new Date(cutoff).toISOString().slice(0, 10);
  const today = new Date().toISOString().slice(0, 10);
  const available = new Set(usageRollup.listAvailableRollups());
  const rollupHits = []; // dates we actually consumed
  const rollupDates = new Set();
  for (const d of available) {
    if (d < cutoffDay) continue; // outside window
    if (d >= today) continue;    // never use a rollup for today
    rollupDates.add(d);
    rollupHits.push(d);
  }

  // Helper: fold a per-bucket aggregate from a rollup file into the
  // working buckets[] map. Used for both granularity modes.
  function mergeRollup(roll) {
    if (!roll || typeof roll !== 'object') return;
    if (gran === 'day') {
      const ts_iso = `${roll.date}T00:00:00.000Z`;
      if (!buckets.has(ts_iso)) {
        buckets.set(ts_iso, {
          ts_iso,
          requests: 0,
          prompt_tokens: 0,
          completion_tokens: 0,
          errors: 0,
          _latency: [],
        });
      }
      const b = buckets.get(ts_iso);
      const g = roll.globals || {};
      b.requests += Number(g.requests) || 0;
      b.prompt_tokens += Number(g.prompt_tokens) || 0;
      b.completion_tokens += Number(g.completion_tokens) || 0;
      b.errors += Number(g.errors) || 0;
      if (Array.isArray(g.latency_samples)) {
        for (const v of g.latency_samples) b._latency.push(v);
      }
      totalRequests += Number(g.requests) || 0;
      totalPrompt += Number(g.prompt_tokens) || 0;
      totalCompletion += Number(g.completion_tokens) || 0;
      totalErrors += Number(g.errors) || 0;
      if (Array.isArray(g.latency_samples)) {
        for (const v of g.latency_samples) allLatency.push(v);
      }
    } else {
      // hour granularity — fan out the rollup's by_hour map.
      const byHour = roll.by_hour || {};
      const g = roll.globals || {};
      for (const hh of Object.keys(byHour)) {
        const ts_iso = `${roll.date}T${hh}:00:00.000Z`;
        const hb = byHour[hh] || {};
        if (!buckets.has(ts_iso)) {
          buckets.set(ts_iso, {
            ts_iso,
            requests: 0,
            prompt_tokens: 0,
            completion_tokens: 0,
            errors: 0,
            _latency: [],
          });
        }
        const b = buckets.get(ts_iso);
        b.requests += Number(hb.requests) || 0;
        b.prompt_tokens += Number(hb.prompt_tokens) || 0;
        b.completion_tokens += Number(hb.completion_tokens) || 0;
        b.errors += Number(hb.errors) || 0;
        if (Array.isArray(hb.latency_samples)) {
          for (const v of hb.latency_samples) b._latency.push(v);
        }
      }
      totalRequests += Number(g.requests) || 0;
      totalPrompt += Number(g.prompt_tokens) || 0;
      totalCompletion += Number(g.completion_tokens) || 0;
      totalErrors += Number(g.errors) || 0;
      if (Array.isArray(g.latency_samples)) {
        for (const v of g.latency_samples) allLatency.push(v);
      }
    }
  }

  for (const d of rollupHits) {
    const roll = usageRollup.readRollup(d);
    mergeRollup(roll);
  }

  // Stream usage.jsonl, SKIPPING rows whose date is covered by a rollup.
  const stats = await streamJsonl(usageFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    if (row.route && row.route !== '/v1/chat/completions') return;
    const day = utcDay(ms);
    if (rollupDates.has(day)) return; // covered by a rollup; skip
    const label = bucketLabel(ms);
    if (!buckets.has(label)) {
      buckets.set(label, {
        ts_iso: label,
        requests: 0,
        prompt_tokens: 0,
        completion_tokens: 0,
        errors: 0,
        _latency: [],
      });
    }
    const b = buckets.get(label);
    b.requests += 1;
    totalRequests += 1;
    const pt = Number(row.prompt_tokens) || 0;
    const ct = Number(row.completion_tokens) || 0;
    b.prompt_tokens += pt;
    b.completion_tokens += ct;
    totalPrompt += pt;
    totalCompletion += ct;
    const lat = Number(row.latency_ms);
    if (Number.isFinite(lat) && lat > 0) {
      b._latency.push(lat);
      allLatency.push(lat);
    }
    if (row.status && row.status !== 'success') {
      b.errors += 1;
      totalErrors += 1;
    }
  });

  const byBucket = Array.from(buckets.values())
    .map((b) => ({
      ts_iso: b.ts_iso,
      requests: b.requests,
      prompt_tokens: b.prompt_tokens,
      completion_tokens: b.completion_tokens,
      p50_latency_ms: percentile(b._latency.slice(), 50),
      p95_latency_ms: percentile(b._latency.slice(), 95),
      errors: b.errors,
    }))
    .sort((a, b) => (a.ts_iso < b.ts_iso ? -1 : 1));

  return {
    by_bucket: byBucket,
    totals: {
      requests: totalRequests,
      prompt_tokens: totalPrompt,
      completion_tokens: totalCompletion,
      p50_latency_ms: percentile(allLatency.slice(), 50),
      p95_latency_ms: percentile(allLatency.slice(), 95),
      errors: totalErrors,
    },
    granularity: gran,
    source: rollupHits.length
      ? `usage.jsonl + ${rollupHits.length} daily rollup(s)`
      : 'usage.jsonl',
    rollup_cache_hit: rollupHits.length > 0,
    rollup_dates: rollupHits,
    since_ms: cutoff,
    skipped_lines: stats.skipped,
  };
}

// ---------------------------------------------------------------------------
// anomaliesByKind
// ---------------------------------------------------------------------------
// Source: anomalies.jsonl. Buckets by `kind` (scanner_active,
// auth_brute_force_suspected, etc — see src/anomaly.js). `recent[]`
// is the last 20 events in chronological order; useful for the
// Management Console "live tail" widget.
async function anomaliesByKind({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const byKind = {};
  const all = [];

  const stats = await streamJsonl(anomaliesFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    const kind = row.kind || 'unknown';
    byKind[kind] = (byKind[kind] || 0) + 1;
    all.push(row);
  });

  // Sort by ts ascending, keep the last 20 (most recent). all[] is
  // bounded by anomalies.jsonl size; for the 100MB scale that's fine.
  all.sort((a, b) => (a.ts < b.ts ? -1 : a.ts > b.ts ? 1 : 0));
  const recent = all.slice(-20);

  return {
    by_kind: byKind,
    recent,
    total: all.length,
    source: 'anomalies.jsonl',
    since_ms: cutoff,
    skipped_lines: stats.skipped,
  };
}

// ---------------------------------------------------------------------------
// honeypotsByPath
// ---------------------------------------------------------------------------
// Source: data/honeypots.jsonl — one row per honeypot hit, appended by
// src/honeypot.js via src/event-log.js. Aggregates count by
// normalized_path (lower-cased + trailing-slash-stripped) so trivial
// scanner variants (/.ENV, /.env/, /Wp-Admin) collapse into the same
// bucket. Falls back to the raw `path` field if a row predates
// normalized_path. On a fresh deploy with no file yet, returns zeros
// and a `note` so the Management Console can render the section
// without fabricating data.
async function honeypotsByPath({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const filePath = honeypotsFile();
  const fileExists = fs.existsSync(filePath);

  const byPath = {};
  let total = 0;

  const stats = await streamJsonl(filePath, (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    // Prefer normalized_path so /.ENV and /.env/ collapse into /.env
    // for the aggregation key. Fall back to the raw path for back-
    // compat with any future row that omits the normalized field.
    const key = (typeof row.normalized_path === 'string' && row.normalized_path)
      ? row.normalized_path
      : (typeof row.path === 'string' && row.path) ? row.path : null;
    if (!key) return;
    byPath[key] = (byPath[key] || 0) + 1;
    total += 1;
  });

  const topPaths = Object.entries(byPath)
    .map(([path_, count]) => ({ path: path_, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 20);

  const out = {
    by_path: byPath,
    total,
    top_paths: topPaths,
    source: 'honeypots.jsonl',
    since_ms: cutoff,
    skipped_lines: stats.skipped,
  };
  // Only emit a `note` when the file is missing — that's the genuine
  // "no events yet" case (fresh deploy). When the file exists, the
  // numbers are real and no caveat is needed.
  if (!fileExists) {
    out.note = 'data/honeypots.jsonl does not exist yet — no honeypot hits have been recorded in this deploy.';
  }
  return out;
}

// ---------------------------------------------------------------------------
// rateLimitsByDay
// ---------------------------------------------------------------------------
// Source: data/rate-limits.jsonl — one row per 429 emitted, appended by
// src/rate-limit.js (per-IP + per-tenant fixed-window caps + anomaly-
// fail-closed bans) and src/chat-api.js enforceDailyCap (per-(tenant,
// app) daily request + token caps). Aggregates count by `kind` and by
// UTC day so the Management Console can plot a stacked-area time-series.
// On a fresh deploy with no file yet, returns zeros + a `note`.
async function rateLimitsByDay({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const filePath = rateLimitsFile();
  const fileExists = fs.existsSync(filePath);

  // Seed every known kind so a Management Console that pre-renders the
  // legend can show all five categories even when one has zero events.
  const byKind = {
    rate_limit_ip: 0,
    rate_limit_tenant: 0,
    daily_quota_request: 0,
    daily_quota_token: 0,
    anomaly_block: 0,
  };
  const byDay = new Map();
  let total = 0;

  const stats = await streamJsonl(filePath, (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    const kind = typeof row.kind === 'string' ? row.kind : 'unknown';
    byKind[kind] = (byKind[kind] || 0) + 1;
    const day = utcDay(ms);
    if (!byDay.has(day)) {
      byDay.set(day, {
        date: day,
        rate_limit_ip: 0,
        rate_limit_tenant: 0,
        daily_quota_request: 0,
        daily_quota_token: 0,
        anomaly_block: 0,
        total: 0,
      });
    }
    const b = byDay.get(day);
    if (kind in b) b[kind] += 1;
    b.total += 1;
    total += 1;
  });

  const out = {
    by_kind: byKind,
    by_day: Array.from(byDay.values()).sort((a, b) => (a.date < b.date ? -1 : 1)),
    total,
    source: 'rate-limits.jsonl',
    since_ms: cutoff,
    skipped_lines: stats.skipped,
  };
  if (!fileExists) {
    out.note = 'data/rate-limits.jsonl does not exist yet — no 429s have been recorded in this deploy.';
  }
  return out;
}

// ---------------------------------------------------------------------------
// tenantsActive
// ---------------------------------------------------------------------------
// Source: usage.jsonl streamed for the window. Active = at least one
// request within sinceMs. Returns:
//   active: count of distinct tenant_ids
//   by_tier: tier rollup (read from keys.json so a tenant maps to the
//     tier on their most-recently-issued key)
//   top_by_usage: top 20 tenants by request count, descending
async function tenantsActive({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);

  // Build tenant_id → tier from keys.json. A tenant with multiple keys
  // gets the tier from their most recently issued non-revoked key (the
  // operator's natural reading: "what plan are they on right now").
  let tenantTier = new Map();
  try {
    const raw = fs.readFileSync(keysFile(), 'utf8');
    const records = JSON.parse(raw);
    if (Array.isArray(records)) {
      const sortedByIssued = records
        .filter((r) => r && r.tenant_id && r.active !== false)
        .sort((a, b) => (a.issued_at < b.issued_at ? 1 : -1));
      for (const r of sortedByIssued) {
        if (!tenantTier.has(r.tenant_id)) {
          tenantTier.set(r.tenant_id, r.tier || 'unknown');
        }
      }
    }
  } catch { tenantTier = new Map(); }

  const seen = new Map(); // tenant_id → { requests, last_seen_ms }
  await streamJsonl(usageFile(), (row) => {
    const ms = toMs(row && row.ts);
    if (!Number.isFinite(ms) || ms < cutoff) return;
    const tid = row.tenant_id;
    if (!tid) return;
    if (!seen.has(tid)) seen.set(tid, { tenant_id: tid, requests: 0, last_seen_ms: 0 });
    const s = seen.get(tid);
    s.requests += 1;
    if (ms > s.last_seen_ms) s.last_seen_ms = ms;
  });

  const byTier = {};
  for (const tid of seen.keys()) {
    const tier = tenantTier.get(tid) || 'unknown';
    byTier[tier] = (byTier[tier] || 0) + 1;
  }

  const topByUsage = Array.from(seen.values())
    .sort((a, b) => b.requests - a.requests)
    .slice(0, 20)
    .map((s) => ({
      tenant_id: s.tenant_id,
      requests: s.requests,
      last_seen_ts: new Date(s.last_seen_ms).toISOString(),
      tier: tenantTier.get(s.tenant_id) || 'unknown',
    }));

  return {
    active: seen.size,
    by_tier: byTier,
    top_by_usage: topByUsage,
    source: 'usage.jsonl + keys.json',
    since_ms: cutoff,
  };
}

// ---------------------------------------------------------------------------
// channelsBySignup — distribution attribution from keys.signup_source
// ---------------------------------------------------------------------------
// Source: keys.json. Every free-tier key issued via POST /signup/free
// carries a signup_source object (set in src/index.js since the
// adopter-instrumentation merge). Pre-attribution keys + operator-
// issued keys have signup_source: null and bucket as 'unknown'.
//
// Aggregation shape:
//   {
//     total: <int>,                          # all signups in window
//     by_utm_source: { hn: 12, twitter: 3, unknown: 8, ... },
//     by_utm_campaign: { launch: 15, ... },
//     by_referer_host: { 'news.ycombinator.com': 12, 'direct': 4, ... },
//     top_referers: [ { host, count }, ... ],  # top 20
//     since_ms: <ms epoch>,
//     source: 'keys.json',
//   }
//
// Referer is reduced to host so /item?id=X and /item?id=Y collapse to
// the same bucket. Direct (no referer header) → 'direct'. Malformed
// referer → 'unknown'.
async function channelsBySignup({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  let records = [];
  try {
    const raw = fs.readFileSync(keysFile(), 'utf8');
    records = JSON.parse(raw);
    if (!Array.isArray(records)) records = [];
  } catch (_e) { records = []; }

  const byUtmSource = {};
  const byUtmCampaign = {};
  const byUtmMedium = {};
  const byRefererHost = {};
  let total = 0;

  for (const r of records) {
    if (!r || !r.issued_at) continue;
    const ms = toMs(r.issued_at);
    if (!Number.isFinite(ms) || ms < cutoff) continue;
    total += 1;
    const src = r.signup_source || null;
    const us = (src && src.utm_source) || 'unknown';
    const uc = (src && src.utm_campaign) || 'unknown';
    const um = (src && src.utm_medium) || 'unknown';
    byUtmSource[us] = (byUtmSource[us] || 0) + 1;
    byUtmCampaign[uc] = (byUtmCampaign[uc] || 0) + 1;
    byUtmMedium[um] = (byUtmMedium[um] || 0) + 1;
    let host = 'direct';
    if (src && src.referer) {
      try {
        host = new URL(src.referer).host || 'unknown';
      } catch (_e) { host = 'unknown'; }
    }
    byRefererHost[host] = (byRefererHost[host] || 0) + 1;
  }

  const topReferers = Object.entries(byRefererHost)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([host, count]) => ({ host, count }));

  return {
    total,
    by_utm_source: byUtmSource,
    by_utm_campaign: byUtmCampaign,
    by_utm_medium: byUtmMedium,
    by_referer_host: byRefererHost,
    top_referers: topReferers,
    since_ms: cutoff,
    source: 'keys.json',
  };
}

// ---------------------------------------------------------------------------
// revenueSnapshot
// ---------------------------------------------------------------------------
// Source: keys.json + packages.json. We do NOT call the Stripe API in
// v1 — the keys.json record's package_id is already a deterministic
// pointer into packages.json which carries monthly_usd. A key counts
// as a live subscription when:
//   - active !== false
//   - stripe_subscription_status === 'active' OR 'trialing'
//   - package_id is set + non-free
//
// This intentionally over-counts trialing customers vs Stripe's actual
// invoicing — the Management Console operator can split the bar chart
// by status if needed. The `note` field calls out that we're computing
// from local state and a Stripe-API integration is a future card.
function revenueSnapshot() {
  let packages = [];
  try {
    const pf = process.env.PACKAGES_FILE || path.join(DATA_DIR, 'packages.json');
    packages = JSON.parse(fs.readFileSync(pf, 'utf8'));
    if (!Array.isArray(packages)) packages = [];
  } catch { packages = []; }
  const priceByPackage = new Map();
  for (const p of packages) {
    if (p && p.id) priceByPackage.set(p.id, Number(p.monthly_usd) || 0);
  }

  let keyRecords = [];
  try {
    keyRecords = JSON.parse(fs.readFileSync(keysFile(), 'utf8'));
    if (!Array.isArray(keyRecords)) keyRecords = [];
  } catch { keyRecords = []; }

  let mrr = 0;
  let activeSubs = 0;
  const byTier = {};

  for (const r of keyRecords) {
    if (!r || r.active === false) continue;
    if (!r.package_id || r.package_id === 'free') continue;
    const status = r.stripe_subscription_status;
    if (status !== 'active' && status !== 'trialing') continue;
    const price = priceByPackage.get(r.package_id) || 0;
    mrr += price;
    activeSubs += 1;
    byTier[r.package_id] = (byTier[r.package_id] || 0) + 1;
  }

  return {
    monthly_recurring_usd: mrr,
    active_subscriptions: activeSubs,
    by_tier: byTier,
    source: 'keys.json + packages.json',
    note: "computed from keys.json package_id + packages.json prices; does NOT call Stripe API. A future card will reconcile with Stripe's subscription state of record.",
  };
}

// ---------------------------------------------------------------------------
// summary — workhorse one-shot endpoint
// ---------------------------------------------------------------------------
// The Management Console "CogOS Analytics" tab fetches THIS endpoint on
// page load. Sections are awaited in parallel so the cost is dominated
// by the slowest stream (usage.jsonl), not the sum.
async function summary({ sinceMs } = {}) {
  const cutoff = resolveSinceMs(sinceMs);
  const [
    signups,
    requests,
    anomalies,
    honeypots,
    rateLimits,
    tenants,
  ] = await Promise.all([
    signupsByDay({ sinceMs: cutoff }),
    requestsByHour({ sinceMs: cutoff, granularity: 'day' }),
    anomaliesByKind({ sinceMs: cutoff }),
    honeypotsByPath({ sinceMs: cutoff }),
    rateLimitsByDay({ sinceMs: cutoff }),
    tenantsActive({ sinceMs: cutoff }),
  ]);
  const revenue = revenueSnapshot();
  return {
    since_ms: cutoff,
    generated_at: new Date().toISOString(),
    signups,
    requests,
    anomalies,
    honeypots,
    rate_limits: rateLimits,
    tenants,
    revenue,
  };
}

module.exports = {
  signupsByDay,
  requestsByHour,
  anomaliesByKind,
  honeypotsByPath,
  rateLimitsByDay,
  tenantsActive,
  channelsBySignup,
  revenueSnapshot,
  summary,
  // Test hooks
  _internal: {
    utcDay,
    utcHourIso,
    utcDayIso,
    percentile,
    resolveSinceMs,
    DEFAULT_WINDOW_MS,
    streamJsonl,
  },
};
